navbar:
  logo: # choose [img] or [icon + title]
    img:
    icon:
    title:
  menu:
    # The following can be written in `blog/source/_data/menu.yml`
    - name: 博客
      icon: fas fa-rss
      url: /
    - name: 分类
      icon: fas fa-folder-open
      url: categories/
    - name: 标签
      icon: fas fa-tags
      url: tags/
    - name: 归档
      icon: fas fa-archive
      url: archives/
    - name: 友链
      icon: fas fa-link
      url: friends/
    - name: 关于
      icon: fas fa-info-circle
      url: about/
  search: 搜索   # Search bar placeholder

plugins:
  ...
  # 文章字数统计、阅读时长，开启需要安装插件: npm i --save hexo-wordcount
  wordcount:
    enable: true

# 文章布局
article:
  ...
  # 文章详情页面的文章卡片本体布局方案
  body:
    # 文章顶部信息
    # 从 meta_library 中取
    top_meta: [..., wordcount, ...]
    ...
    # 文章底部信息
    # 从 meta_library 中取
    bottom_meta: [..., wordcount, ...]

# rightmenu:
#   enable: true
#   # hr: 分割线, music: 音乐控制器
#   layout: [home, help, examples, contributors, hr, source_docs, source_theme, hr, print, hr, music]
#   # 可选功能项
#   print:
#     name: 打印页面
#     icon: fa fa-print
#     onclick: document.execCommand('print')
#   # 自定义菜单的格式如下
#   help:
#     name: 常见问题
#     icon: fa fa-question
#     url: https://volantis.js.org/faqs/
#   examples:
#     name: 示例博客
#     icon: fa fa-rss
#     url: https://volantis.js.org/examples/
#   contributors:
#     name: 加入社区
#     icon: fa fa-fan fa-spin
#     url: https://volantis.js.org/contributors/
#   source_docs:
#     name: 本站源码
#     icon: fa fa-code-branch
#     url: https://github.com/volantis-x/volantis-docs/
#   source_theme:
#     name: 主题源码
#     icon: fa fa-code-branch
#     url: https://github.com/volantis-x/hexo-theme-volantis/
  